server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-examples?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
